# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    # ID to load the MSP definition as
    ID: OrdererMSP
    # MSPDir is the filesystem path which contains the MSP configuration
    MSPDir: ../organizations/ordererOrganizations/drugcounterfeit.com/msp
    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.drugcounterfeit.com:7050

  - &consumer
    Name: consumerMSP
    # ID to load the MSP definition as
    ID: consumerMSP
    MSPDir: ../organizations/peerOrganizations/consumer.drugcounterfeit.com/msp
    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('consumerMSP.admin', 'consumerMSP.peer', 'consumerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('consumerMSP.admin', 'consumerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('consumerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('consumerMSP.peer')"

  - &distributor
    Name: distributorMSP
    # ID to load the MSP definition as
    ID: distributorMSP
    MSPDir: ../organizations/peerOrganizations/distributor.drugcounterfeit.com/msp
    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.peer', 'distributorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('distributorMSP.admin', 'distributorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('distributorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('distributorMSP.peer')"

  - &manufacturer
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: manufacturerMSP
    # ID to load the MSP definition as
    ID: manufacturerMSP
    MSPDir: ../organizations/peerOrganizations/manufacturer.drugcounterfeit.com/msp
    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.peer', 'manufacturerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('manufacturerMSP.admin', 'manufacturerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('manufacturerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('manufacturerMSP.peer')"

  - &retailer
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: retailerMSP
    # ID to load the MSP definition as
    ID: retailerMSP
    MSPDir: ../organizations/peerOrganizations/retailer.drugcounterfeit.com/msp
    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.peer', 'retailerMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('retailerMSP.admin', 'retailerMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('retailerMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('retailerMSP.peer')"

  - &transporter
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: transporterMSP
    # ID to load the MSP definition as
    ID: transporterMSP
    MSPDir: ../organizations/peerOrganizations/transporter.drugcounterfeit.com/msp
    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('transporterMSP.admin', 'transporterMSP.peer', 'transporterMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('transporterMSP.admin', 'transporterMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('transporterMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('transporterMSP.peer')"

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true


Application: &ApplicationDefaults
  Organizations:
  # Policies defines the set of policies at this level of the config tree
  # For Application policies, their canonical path is
  #   /Channel/Application/<PolicyName>
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities


Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.drugcounterfeit.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.drugcounterfeit.com
        Port: 7050
        ClientTLSCert: ../organizations/ordererOrganizations/drugcounterfeit.com/orderers/orderer.drugcounterfeit.com/tls/server.crt
        ServerTLSCert: ../organizations/ordererOrganizations/drugcounterfeit.com/orderers/orderer.drugcounterfeit.com/tls/server.crt
  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s
  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    # Max Message Count: The maximum number of messages to permit in a batch
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  # Policies defines the set of policies at this level of the config tree
  # For Orderer policies, their canonical path is
  #   /Channel/Orderer/<PolicyName>
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"


Channel: &ChannelDefaults
  # Policies defines the set of policies at this level of the config tree
  # For Channel policies, their canonical path is
  #   /Channel/<PolicyName>
  Policies:
    # Who may invoke the 'Deliver' API
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    # Who may invoke the 'Broadcast' API
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    # By default, who may modify elements at this config level
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities


Profiles:

  DrugCounterfeitOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      DrugCounterfeitConsortium:
        Organizations:
          - *consumer
          - *distributor
          - *manufacturer
          - *retailer
          - *transporter

  DrugCounterfeitChannel:
    Consortium: DrugCounterfeitConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *consumer
        - *distributor
        - *manufacturer
        - *retailer
        - *transporter
      Capabilities:
        <<: *ApplicationCapabilities